
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}

  data:
    cassandra:
      keyspace-name: main
      username: ${USERNAME}
      password: ${PASSWORD}
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: betterreads

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: ${ID}
  region: ${REGION}
  keyspace: main
  application.token: ${APPLICATION_TOKEN}
server:
  port: 8080
